<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WestAfricaCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seed West African countries with currencies and locales
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Côte d\'Ivoire',
                'code' => 'CI',
                'phone_code' => '+225',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇨🇮',
                'locale' => 'fr_CI',
                'timezone' => 'Africa/Abidjan',
                'latitude' => 7.5400,
                'longitude' => -5.5471,
                'min_lat' => 4.3600,
                'max_lat' => 10.7400,
                'min_lng' => -8.6019,
                'max_lng' => -2.4930,
                'is_active' => true,
            ],
            [
                'name' => 'Sénégal',
                'code' => 'SN',
                'phone_code' => '+221',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇸🇳',
                'locale' => 'fr_SN',
                'timezone' => 'Africa/Dakar',
                'latitude' => 14.4974,
                'longitude' => -14.4524,
                'min_lat' => 12.0000,
                'max_lat' => 16.7000,
                'min_lng' => -17.5350,
                'max_lng' => -11.3550,
                'is_active' => false,
            ],
            [
                'name' => 'Mali',
                'code' => 'ML',
                'phone_code' => '+223',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇲🇱',
                'locale' => 'fr_ML',
                'timezone' => 'Africa/Bamako',
                'latitude' => 17.5707,
                'longitude' => -3.9962,
                'min_lat' => 10.1400,
                'max_lat' => 25.0000,
                'min_lng' => -12.2408,
                'max_lng' => 4.2673,
                'is_active' => false,
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'phone_code' => '+226',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇧🇫',
                'locale' => 'fr_BF',
                'timezone' => 'Africa/Ouagadougou',
                'latitude' => 12.3641,
                'longitude' => -1.5275,
                'min_lat' => 9.4000,
                'max_lat' => 15.0800,
                'min_lng' => -5.5200,
                'max_lng' => 2.4000,
                'is_active' => false,
            ],
            [
                'name' => 'Niger',
                'code' => 'NE',
                'phone_code' => '+227',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇳🇪',
                'locale' => 'fr_NE',
                'timezone' => 'Africa/Niamey',
                'latitude' => 17.6078,
                'longitude' => 8.0817,
                'min_lat' => 11.7000,
                'max_lat' => 23.5200,
                'min_lng' => 0.1750,
                'max_lng' => 15.9000,
                'is_active' => false,
            ],
            [
                'name' => 'Togo',
                'code' => 'TG',
                'phone_code' => '+228',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇹🇬',
                'locale' => 'fr_TG',
                'timezone' => 'Africa/Lome',
                'latitude' => 8.6195,
                'longitude' => 0.8248,
                'min_lat' => 6.1000,
                'max_lat' => 11.1400,
                'min_lng' => -0.1490,
                'max_lng' => 1.8080,
                'is_active' => false,
            ],
            [
                'name' => 'Bénin',
                'code' => 'BJ',
                'phone_code' => '+229',
                'currency' => 'XOF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA',
                'flag_emoji' => '🇧🇯',
                'locale' => 'fr_BJ',
                'timezone' => 'Africa/Porto-Novo',
                'latitude' => 9.3077,
                'longitude' => 2.3158,
                'min_lat' => 6.2300,
                'max_lat' => 12.4200,
                'min_lng' => 0.7750,
                'max_lng' => 3.8510,
                'is_active' => false,
            ],
            [
                'name' => 'Guinée',
                'code' => 'GN',
                'phone_code' => '+224',
                'currency' => 'GNF',
                'currency_symbol' => 'GNF',
                'currency_name' => 'Franc Guinéen',
                'flag_emoji' => '🇬🇳',
                'locale' => 'fr_GN',
                'timezone' => 'Africa/Conakry',
                'latitude' => 11.2874,
                'longitude' => -11.7811,
                'min_lat' => 7.2000,
                'max_lat' => 15.0900,
                'min_lng' => -15.1300,
                'max_lng' => -7.6400,
                'is_active' => false,
            ],
            [
                'name' => 'Ghana',
                'code' => 'GH',
                'phone_code' => '+233',
                'currency' => 'GHS',
                'currency_symbol' => 'GH₵',
                'currency_name' => 'Cedi Ghanéen',
                'flag_emoji' => '🇬🇭',
                'locale' => 'en_GH',
                'timezone' => 'Africa/Accra',
                'latitude' => 7.9465,
                'longitude' => -1.0232,
                'min_lat' => 4.7380,
                'max_lat' => 11.1730,
                'min_lng' => -3.2590,
                'max_lng' => 1.1970,
                'is_active' => false,
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NG',
                'phone_code' => '+234',
                'currency' => 'NGN',
                'currency_symbol' => '₦',
                'currency_name' => 'Naira',
                'flag_emoji' => '🇳🇬',
                'locale' => 'en_NG',
                'timezone' => 'Africa/Lagos',
                'latitude' => 9.0820,
                'longitude' => 8.6753,
                'min_lat' => 4.2700,
                'max_lat' => 13.8900,
                'min_lng' => 2.6680,
                'max_lng' => 14.6780,
                'is_active' => false,
            ],
            [
                'name' => 'Cameroun',
                'code' => 'CM',
                'phone_code' => '+237',
                'currency' => 'XAF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA (CEMAC)',
                'flag_emoji' => '🇨🇲',
                'locale' => 'fr_CM',
                'timezone' => 'Africa/Douala',
                'latitude' => 5.6963,
                'longitude' => 12.4139,
                'min_lat' => 1.6540,
                'max_lat' => 13.0830,
                'min_lng' => 8.4960,
                'max_lng' => 16.1930,
                'is_active' => false,
            ],
            [
                'name' => 'Gabon',
                'code' => 'GA',
                'phone_code' => '+241',
                'currency' => 'XAF',
                'currency_symbol' => 'FCFA',
                'currency_name' => 'Franc CFA (CEMAC)',
                'flag_emoji' => '🇬🇦',
                'locale' => 'fr_GA',
                'timezone' => 'Africa/Libreville',
                'latitude' => -0.8037,
                'longitude' => 11.6094,
                'min_lat' => -3.9280,
                'max_lat' => 2.3180,
                'min_lng' => 8.6950,
                'max_lng' => 14.5250,
                'is_active' => false,
            ],
        ];

        foreach ($countries as $countryData) {
            // Check if country exists
            $existing = DB::table('countries')->where('code', $countryData['code'])->first();

            if ($existing) {
                // Update existing
                DB::table('countries')
                    ->where('code', $countryData['code'])
                    ->update([
                        'phone_code' => $countryData['phone_code'],
                        'currency' => $countryData['currency'],
                        'currency_symbol' => $countryData['currency_symbol'],
                        'currency_name' => $countryData['currency_name'],
                        'flag_emoji' => $countryData['flag_emoji'],
                        'locale' => $countryData['locale'],
                        'timezone' => $countryData['timezone'],
                        'updated_at' => now(),
                    ]);
            } else {
                // Create new
                DB::table('countries')->insert([
                    ...$countryData,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }

        $this->command->info('West African countries seeded successfully!');
    }
}
