<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Photo extends Model
{
    use HasFactory;

    protected $fillable = [
        'residence_id',
        'path',
        'order',
        'is_primary',
        'is_optimized',
        'tags',
        'room_type',
        'moderation_status',
        'moderation_reason',
        'quality_score',
        'quality_issues',
        'safe_search_data',
        'labels_data',
        'image_hash',
        'is_property_photo',
    ];

    protected $casts = [
        'is_primary'       => 'boolean',
        'is_optimized'     => 'boolean',
        'is_property_photo' => 'boolean',
        'tags'             => 'array',
        'quality_issues'   => 'array',
        'safe_search_data' => 'array',
        'labels_data'      => 'array',
    ];

    // ── Scopes ──

    public function scopeApproved($query)
    {
        return $query->whereIn('moderation_status', ['approved', 'pending', 'skipped']);
    }

    public function scopeRejected($query)
    {
        return $query->where('moderation_status', 'rejected');
    }

    public function scopeNeedsReview($query)
    {
        return $query->where('moderation_status', 'review');
    }

    public function scopeByRoom($query, string $roomType)
    {
        return $query->where('room_type', $roomType);
    }

    // ── Helpers ──

    public function isModerated(): bool
    {
        return !in_array($this->moderation_status, ['pending', null]);
    }

    public function isSafe(): bool
    {
        return in_array($this->moderation_status, ['approved', 'skipped', 'pending', null]);
    }

    /**
     * Residence that owns this photo
     */
    public function residence()
    {
        return $this->belongsTo(Residence::class);
    }

    /**
     * Get the full URL of the photo
     * Handles both local storage paths and external URLs (e.g. Unsplash)
     */
    public function getUrlAttribute(): string
    {
        return \storage_url($this->path);
    }

    /**
     * Get the thumbnail URL (generated by OptimizeResidencePhoto job).
     * Falls back to the original URL if the thumbnail has not been generated yet.
     */
    public function getThumbnailUrlAttribute(): string
    {
        if ($this->is_optimized && !str_starts_with($this->path, 'http')) {
            $thumbPath = preg_replace('/(\.\w+)$/i', '_thumb$1', $this->path);
            if ($thumbPath !== $this->path && Storage::disk('public')->exists($thumbPath)) {
                return \storage_url($thumbPath);
            }
        }

        return $this->url;
    }

    /**
     * Placeholder used when the photo file is missing from storage
     */
    public static function placeholder(): string
    {
        return asset('images/placeholder-residence.jpg');
    }

    /**
     * Delete photo file when model is deleted
     */
    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($photo) {
            if (str_starts_with($photo->path, 'http')) {
                return; // URL externe, rien à supprimer
            }

            $disk = Storage::disk('public');

            // Supprimer l'original
            if ($disk->exists($photo->path)) {
                $disk->delete($photo->path);
            }

            // Supprimer la version WebP
            $webpPath = preg_replace('/\.(jpe?g|png)$/i', '.webp', $photo->path);
            if ($webpPath !== $photo->path && $disk->exists($webpPath)) {
                $disk->delete($webpPath);
            }

            // Supprimer la miniature JPEG
            $thumbPath = preg_replace('/(\.[\w]+)$/i', '_thumb$1', $photo->path);
            if ($thumbPath !== $photo->path && $disk->exists($thumbPath)) {
                $disk->delete($thumbPath);
            }

            // Supprimer la miniature WebP
            $thumbWebpPath = preg_replace('/\.(jpe?g|png)$/i', '.webp', $thumbPath);
            if ($thumbWebpPath !== $thumbPath && $disk->exists($thumbWebpPath)) {
                $disk->delete($thumbWebpPath);
            }
        });
    }
}
