<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;

class SeoData extends Model
{
    protected $table = 'seo_data';

    protected $fillable = [
        'seoable_type',
        'seoable_id',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'og_title',
        'og_description',
        'og_image',
        'structured_data',
        'canonical_url',
        'robots',
        'locale',
        'auto_generated',
    ];

    protected $casts = [
        'meta_keywords' => 'array',
        'structured_data' => 'array',
        'auto_generated' => 'boolean',
    ];

    // ===== RELATIONSHIPS =====

    public function seoable(): MorphTo
    {
        return $this->morphTo();
    }

    // ===== SCOPES =====

    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }

    public function scopeManuallyEdited($query)
    {
        return $query->where('auto_generated', false);
    }

    public function scopeForLocale($query, string $locale)
    {
        return $query->where('locale', $locale);
    }

    // ===== HELPERS =====

    /**
     * Obtenir ou créer les données SEO pour un modèle
     */
    public static function forModel(Model $model, string $locale = 'fr'): ?self
    {
        return self::where('seoable_type', get_class($model))
            ->where('seoable_id', $model->id)
            ->where('locale', $locale)
            ->first();
    }

    /**
     * Générer les balises meta HTML
     */
    public function toMetaTags(): string
    {
        $tags = [];

        if ($this->meta_title) {
            $tags[] = '<title>' . e($this->meta_title) . '</title>';
            $tags[] = '<meta name="title" content="' . e($this->meta_title) . '">';
        }

        if ($this->meta_description) {
            $tags[] = '<meta name="description" content="' . e($this->meta_description) . '">';
        }

        if ($this->meta_keywords && count($this->meta_keywords) > 0) {
            $tags[] = '<meta name="keywords" content="' . e(implode(', ', $this->meta_keywords)) . '">';
        }

        if ($this->robots) {
            $tags[] = '<meta name="robots" content="' . e($this->robots) . '">';
        }

        if ($this->canonical_url) {
            $tags[] = '<link rel="canonical" href="' . e($this->canonical_url) . '">';
        }

        // Open Graph
        if ($this->og_title) {
            $tags[] = '<meta property="og:title" content="' . e($this->og_title) . '">';
        }

        if ($this->og_description) {
            $tags[] = '<meta property="og:description" content="' . e($this->og_description) . '">';
        }

        if ($this->og_image) {
            $tags[] = '<meta property="og:image" content="' . e($this->og_image) . '">';
        }

        $tags[] = '<meta property="og:type" content="website">';
        $tags[] = '<meta property="og:locale" content="' . e($this->locale ?? 'fr_FR') . '">';

        // Twitter Card
        $tags[] = '<meta name="twitter:card" content="summary_large_image">';
        if ($this->og_title) {
            $tags[] = '<meta name="twitter:title" content="' . e($this->og_title) . '">';
        }
        if ($this->og_description) {
            $tags[] = '<meta name="twitter:description" content="' . e($this->og_description) . '">';
        }
        if ($this->og_image) {
            $tags[] = '<meta name="twitter:image" content="' . e($this->og_image) . '">';
        }

        return implode("\n    ", $tags);
    }

    /**
     * Générer le JSON-LD structuré
     */
    public function toJsonLd(): string
    {
        if (!$this->structured_data) {
            return '';
        }

        return '<script type="application/ld+json">' . json_encode($this->structured_data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . '</script>';
    }

    /**
     * Obtenir toutes les données SEO formatées pour la vue
     */
    public function toArray(): array
    {
        return [
            'title' => $this->meta_title,
            'description' => $this->meta_description,
            'keywords' => $this->meta_keywords,
            'og' => [
                'title' => $this->og_title,
                'description' => $this->og_description,
                'image' => $this->og_image,
            ],
            'canonical' => $this->canonical_url,
            'robots' => $this->robots,
            'structured_data' => $this->structured_data,
            'meta_tags' => $this->toMetaTags(),
            'json_ld' => $this->toJsonLd(),
        ];
    }
}
